env:
  global:
    - secure: vshHunCbIHWagTIL1tlly1mUZn1+ISL2caARS5s++5lGLvNo2VVnqePlgTgXPqNt6bJ6p+tlfxCeVp2BVQLwM/0V2HLY4/Z6xq14J8syBVhRvH0Gw9F5pq68ddOTqUKQPtDMawWLhOOrs0VyM+yXR49IILn/BZsKGAbQOUiVgQj+YH741zuRBr3zfC7v5Dm1KC8sy2iS+pJodcOAN6e7FUxGiObkrQdnPJEngXt3OzODCbuG6EpwLZloVxjj1jK+AHbDuyzIu0gwGA7EHp/9bN8ELH3MYWH2ROKOXPoc0MI8oppIEtulv6MAWmNOaRc0rNiS74iXNENw9WVARddQyFSEWwVcEa8uj/q9hUBsTzZW0Hkt80lQO3Ovka5UubRqGr/1mTukbK29cptiBVp3DFmDu9UmY6VRFHlLfB+7S+JNSLdjngUzsjvQgzd5YVXvPmD9rkcOZrmW/5byG6sbTFM9AAbCkQVtZlcg3N4F1GIfv4Mj4Ij0ZPPG4d5OO1ybQ5gaaHLWtXnnx2r8R9VCQo6kK+MFz/nhR/AijmBYR8PaqdioFciBb3LC1jjSUsSZELZAGIBiPbWburnLr5lr47DpJ5/O0quY7lJvrN8r7GDOZu6Sc/3LQSeOC/ZLOIsTw0Dp+7qFe/TJ3HtzXOvQPgdHIfE9tFf+0tXZSBtjU3c=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/adblock-nocoin-list
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
