env:
  global:
    - secure: BbrQTcVg/UrMZN027HqACwG7Du+b8u+qs5t30lyfsoGVMBpJ6AC5k74+dtUCG+CM/VukD25Vhc37DmdNs2bN1A8RKXsE9wh7gR2j4Po3OY75KHmUzkDc+DT8on6kCeNVz9GUEq+zKVigSExFQwKq+dRGWflNtUEQWAkSkG4n9fIoZkVI2SRnPwHxTpfJOkP+5Il4WQjFC8KZqqL3zUV5rgp/OWYdHH0f+iHuCMsYoXstuJZoMhjEG6bLOdPengabBQz/MO1z+t3DLRPF+oMoVDSToJdhX1WtKWia3bSkhonXCySkVY6jTy5+ZyQpnQCtURm4T50ZedWc+1aE3+PKQPFlqBv4EA98GSQsfuZCTOi0tmbB1g6lW5feBaS8yoYbnsoV3EyZKves0oFRpCuhCqKvSYnME0fKr6xoBirqNxv/sqdyy7BOE+Ssrxv8DbHYmI+QrnIx0KSj2fDiUeBap+825MDAqB9H17isBB9kKph/nm03+/IK27PHqc2n6OtNQcqiBUTJYSh74oWR4wS+D7lCdlGWCKQghB97C/eUc1TiwxqqAx5naIosEKmqpmr+dWHTKZz+0d+d7FZupm/2tagKj7abCjK6lH08DfNdhYVHtQhMoZkEE8c5Bg8RB14J8+Feds2P/TJDVMJ1HeMRvVOnjkWCQ0bG18K8sr76FmE=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/adblock-nocoin-list
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
