env:
  global:
    - secure: Csq8JYIOw37UqChqfq5IgUCyTHZuh4Hgr+v+OJjsgp9ldtfAD1cXkwvwDES34UTzCO6b0pvYmdRv+vx7xIAYJo6BJt1mEOgCiHAXJGxYa9IHINtv+p8dq2tjwNEMAOLRpnaSfSv/tTkfWDU76tjiu6ZzEQh/gcQWx0Ccq7tYtG8w3pF+uBziQPTD+a0lf+9UInDvvYR5tr5O9B615x9lEdg58rNQ6h9i64gdD9EwYKFpWQksyr533JF+hdnEp6mxRgIfYz5Kq6CuGR9S6wu0qNvM304ssGNaLyTAJMW5Ve8527IXQp7jSjZX0k05PIe3HrD25cVVhpqkoACjcvRjZRz1rwWXsiYv9j4H4QwQ31+jE1Q1WZUYO/517Ao+lIf6t4GTdW7BIHtf4zw29lfas6GfHN7W+Sy1cwAxCH4sLMJ99McCpSM0MVZr2ZidvyfQTgM3ju5ND6DiUrVgWR59MBHe7f67cRmV30DRgDsivjlDBe4Ys+/MRQRmsxZa2NQxqe5R2BmM2VCnYETeeRPi1xtTny5upKH38xiB1+QPvi3I9h3A/eo6p+KMi1Sn4EiyCIlaLqIiihMIaUbLYjw9JPMEq2CZnc44Iy1a187OjjFriSFhvAdAztzZjPgZkqayGSNpvMsnkON0V+W1cs1ZsvCKsWZ+VPwD22VgveimIu0=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/adblock-nocoin-list
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
