env:
  global:
    - secure: GF5sYd05RB3bi7CqdXCkFb0DlkrwG6I7hc6hUJUkJ1TBUXFeIX4ANkifAMsrE3vLxyvM5XAxUH4XrOgDYydQ++os3TJUD7SRVTmXd38mBzDL+dQ1BmUXP/sA/ZRD1nlWJyZyT7K+DHGqDGULe+dF4+AurHWwhO+tz90Wt91zzwycn7XiVnHjztP4cymEEqz3nTZlMWggPyNrFIjoj0G0Qu50y72UrQ/wpLRxc+ekHYxwaoG+Tia531A7O7P/0J+dAstBqlvo+rQv40rXXigr6vg3hBugIseAvqaVod5yU10JoDtxrUghMVXzmObyb/JkjA+Iz1Z+mpZc+e6i2n3oXE70BDl8+DT/zCR/a2zQ6IBvtDYAYVQBPCGj/qASNry+yjYAVGsG6YwyHmfnxtK4OBjtoY/SrX8g3dWH9gzuEhDU4XmZPQQZmKnupgplqsAVefHxw+/plGZXUdpuiyAOWbIiyOHPVPx/zn4duiYNC7S9yTgyJHXSb64GBaDgl94+FTBQn+ZFNrBOAiNFS9U8AWhX0c+Rm5onheKRMvgPMEfQvhapJe0VtbLZdWt8euihuBKxswzO8aj2glu1EJsyzKcpIg9Igo1ht/YQKhsrWWu+YyBat42oYZ8+VxefoETzlR7MTvxsD3ioY26SZgZMtgMLywng7G4JdLBuk3Pd9LM=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/adblock-nocoin-list
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
