env:
  global:
    - secure: UJQmW4oEVbpqu2QUY6PpjrJs/hKaKeHF5dQ78Nop+C/LsXWFZOeALbtuJP1ZncOTJ7DG7kvkADj3slsxAbc3BnhAneP3hb93/GpoSZ7ZIslFUenJJWEaWP13Y6TkjBmh/SnMCkl8xwRAPaxz7GpFbFFKYHcVErHGQ+WyJxiKW4Nvd52u///FYk5p7QFU22yq64U3xTDi+A9CI8/j3nvnaK0KyJ6E70mpHPoKGYiQXkzWo6N+f1z+grb2i8TzyeNb2/u0fP57Ds/GIw/p2bGQlwjh5kiPamXA1ogaVGD30J6+O1zQQL7JJp5KNXWmJkPpJoUxeLZMFTrfEDKSImyNpvS65nN9n/KvxxkRakz6l4LEH7C6PMvOo/lc3lNrd4W0M7kI64Qa5N8R28rl2h1XsQ3YgfEOwCbJaLYffYhNrzQV6rdaHk3/9vcz9fGNPYjKYbwOkG9aVGaRdaeekKzGWbxLpioIReps80Wnb/Yd/sS9vNEXTm0ytpB0+354MpvCvbFm6bws0EYyLGt3fTlzd1SmrqwZVdMdgb3ocYSc5MC2KF1CpsB8CT6k+2JInK9HW2n9KP6EPgnyE9u38qEXUPQbkxGh2BIraK3/dKPCiM2SmWDo3TWviH6gWqq9OChu0cdqliES/xzpZ0YfzuUZdKiBu1QBsBn0tu/4P69R85w=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/adblock-nocoin-list
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
